# Generated by Django 4.2.4 on 2023-10-31 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0017_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 10, 31, 14, 2, 56, 549571, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
